import{a as f,i as d,S as y}from"./assets/vendor-luKj5phc.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))t(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function i(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function t(o){if(o.ep)return;o.ep=!0;const a=i(o);fetch(o.href,a)}})();function m(r,e){const i=r.map(t=>`<li class="gallery-item">
          <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" width="360" height="152"/>
            <div class="text-content-box">
                <p class="image-text"><span class="image-title">Likes</span> ${t.likes}</p>
                <p class="image-text"><span class="image-title">Views</span> ${t.views}</p>
                <p class="image-text"><span class="image-title">Comments</span> ${t.comments}</p>
                <p class="image-text"><span class="image-title">Downloads</span> ${t.downloads}</p>
            </div>
        </a>
      </li>`).join("");e.insertAdjacentHTML("beforeend",i)}function u(r){r.innerHTML=""}class b{constructor(){this.searchQuery="",this.page=1,this.perPage=15,this.baseUrl="https://pixabay.com/api/",this.loadMoreButton=document.querySelector(".js-load-more-btn")}async fetchImages(){const e=`${this.baseUrl}?key=42616276-59c99055eec179e7b1bf68313&q=${this.searchQuery}&lang=en&per_page=${this.perPage}&page=${this.page}`;this.incrementPage();try{const t=(await f.get(e)).data;if(this.totalHits=t.totalHits,t.total===0){p(),this.loadMoreButton.style.display="none";return}return t.hits.length<this.perPage&&(this.loadMoreButton.disabled=!0,this.loadMoreButton.style.display="none",g()),t.hits}catch(i){g(),this.loadMoreButton.style.display="none",console.log(i)}}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.searchQuery}set query(e){this.searchQuery=e}}function p(r){d.show({message:"Sorry, there are no images matching <br> your search query. Please, try again!",position:"topRight",timeout:5e3,backgroundColor:"#ef4040",messageColor:"#ffffff",messageSize:"12",close:!0,closeOnEscape:!0,progressBarColor:"#B51B1B",progressBar:!0,layout:2,maxWidth:432,maxHeigth:88,animateInside:!0,iconUrl:"./img/x-octagon.svg",transitionIn:"fadeInRight",transitionOut:"fadeOutRight"})}function g(){d.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3,backgroundColor:"#4e75ff",messageColor:"#ffffff",messageSize:"12",close:!0,closeOnEscape:!0,progressBarColor:"#ffffff",progressBar:!0,layout:2,maxWidth:432,maxHeigth:88,animateInside:!0,transitionIn:"fadeInRight",transitionOut:"fadeOutRight"})}const s={searchForm:document.querySelector(".js-search-form"),waitingText:document.querySelector(".js-waiting-text"),imagesContainer:document.querySelector(".js-images-container"),loadMoreButton:document.querySelector(".js-load-more-btn")},n=new b;s.searchForm.addEventListener("submit",x);s.loadMoreButton.addEventListener("click",w);async function x(r){if(r.preventDefault(),s.waitingText.style.display="block",n.query=r.currentTarget.elements.query.value,n.resetPage(),n.query===""){p(),c(),s.loadMoreButton.style.display="none",u(s.imagesContainer);return}try{const e=await n.fetchImages();s.loadMoreButton.style.display="block",c(),u(s.imagesContainer),m(e,s.imagesContainer),h()}catch{s.loadMoreButton.style.display="none",console.log("Failed to load more images")}s.searchForm.reset()}async function w(r){r.preventDefault(),s.waitingText.style.display="block";try{const e=await n.fetchImages();c(),m(e,s.imagesContainer),h(),window.scrollBy({top:document.querySelector(".gallery-item").getBoundingClientRect().height*2,behavior:"smooth"})}catch{console.log("Failed to load more images")}}function c(){s.waitingText.style.display="none"}function h(){new y(".images a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
