import{i as m,S as p}from"./assets/vendor-DpkYgfyi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function f(s,t){const a=s.map(i=>`<li class="gallery-item">
          <a href="${i.largeImageURL}">
            <img src="${i.webformatURL}" alt="${i.tags}" width="360" height="200"/>
            <div class="text-content-box">
                <p class="image-text"><span class="image-title">Likes</span> ${i.likes}</p>
                <p class="image-text"><span class="image-title">Views</span> ${i.views}</p>
                <p class="image-text"><span class="image-title">Comments</span> ${i.comments}</p>
                <p class="image-text"><span class="image-title">Downloads</span> ${i.downloads}</p>
            </div>
        </a>
      </li>`).join("");t.insertAdjacentHTML("beforeend",a)}function g(s){s.innerHTML=""}const h="https://pixabay.com/api/";class d{constructor(){this.searchQuery="",this.page=1}fetchImages(){const t=`${h}?key=42616276-59c99055eec179e7b1bf68313&q=${this.searchQuery}&lang=en&per_page=15&Page=${this.page}`;return fetch(t).then(a=>a.json()).then(a=>(a.total===0&&l(),this.incrementPage(),a.hits))}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.searchQuery}set query(t){this.searchQuery=t}}function l(s){m.show({message:"Sorry, there are no images matching <br> your search query. Please, try again!",position:"topRight",timeout:5e3,backgroundColor:"#ef4040",messageColor:"#ffffff",messageSize:"12",close:!0,closeOnEscape:!0,progressBarColor:"#B51B1B",progressBar:!0,layout:2,maxWidth:432,maxHeigth:88,animateInside:!0,iconUrl:"./img/x-octagon.svg",transitionIn:"fadeInRight",transitionOut:"fadeOutRight"})}const n={searchForm:document.querySelector(".js-search-form"),waitingText:document.querySelector(".js-waiting-text"),imagesContainer:document.querySelector(".js-images-container")},o=new d;n.searchForm.addEventListener("submit",y);function y(s){if(s.preventDefault(),n.waitingText.style.display="block",o.query=s.currentTarget.elements.query.value,o.resetPage(),o.query===""){l(),u(),g(n.imagesContainer);return}o.fetchImages().then(t=>{u(),g(n.imagesContainer),f(t,n.imagesContainer),x()}).catch(t=>{l()}),n.searchForm.reset()}function u(){n.waitingText.style.display="none"}function x(){new p(".images a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
